name: Build and Push Container Image
on:
  release:
    types: ["published"]
jobs:
  build-push:
    name: Build and Push Container Image
    runs-on: ubuntu-latest-m
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and Push
      uses: stafftastic/docker-build-push-action@nix
      with:
        name: webapp
        project: stafftastic
        repository: base-images
        serviceAccountKey: ${{secrets.GOOGLE_ARTIFACT_REGISTRY_SA_KEY}}
